### ISSUE TITLE
DataGridView container Bounds

### ISSUE THREAD

**Issue by Massimo1167** [unipsycho/LabVIEWdotNetDataGrid#22]
I realized that if I create a table with no button or link controls, setup is much faster, but to speed up further I saw that you simply resize to the minimum size the DataGridView container before setup and then set it to the original size.
This benefit does not have if the container is simply hidden (labview properties).

![speed up datagridview example](https://cloud.githubusercontent.com/assets/26205452/23603001/66be75ea-0253-11e7-942b-2a0c9908fed8.png)

To improve the "Easy Color Columns.vi" function is better to Show the grid at the end of setup instead of in the function "Apply Column Setup After Binding.vi".
![apply column setup after binding](https://cloud.githubusercontent.com/assets/26205452/23603234/7e6d6cf4-0254-11e7-9534-6abf3edaa4a4.png)

**Comment by unipsycho** [comment]
Hey thanks for the idea here.  Testing this seems fairly minimal, but definitely an improvement.  I need to keep the grid working from a single VI(which is why the grid SHOW property is in the main grid VI.  Adding the OPTIONAL grid colors is not required to use the grid, so I don't want to remove the show from the 1VI function for easy setup.  Best bet is to override this in your code if you need the advantage on that.  So, I don't plan to make this change for simplicity sake.  Thanks for the idea though and to help others with this suggestion if they need it!
