### ISSUE TITLE
2 Questions/Issues

### ISSUE THREAD

**Issue by smXplorer** [unipsycho/LabVIEWdotNetDataGrid#5]
I tried the tool and noticed two potential limitations so far:
- you cannot have different columns with the same name. It would be useful to be at least able to have the displayed column name be different from its internal "label" (i.e. distinguish caption from label)
- when stopping the VI using a .Net datagrid, the .Net container ends up empty. It would be nice to be able to still use the object even if the VI is not running.

Other comments/questions:
- is it possible to justify the display on a column by column, row by row or cell by cell basis? How?
- The up or down triangle appearing when clicking on a column header are not visible by default or even after such a sorting action has been applied to a column. This could result in some confusion (such as "did I already sort this column?")

Anyway, looking good so far! keep up the good work.

**Comment by unipsycho** [comment]
Thanks for the feedback.  I'll look into these issues.

Unfortunately, the one of the container blanking out after stopping the VI, its impossible to change and simple a way that LabVIEW allocates the .net container at run time.  It is annoying though I agree to not be able to see it when the VI is not running, don't think there is anyway around it.

**Comment by unipsycho** [comment]
I think you can use the set cell style VI to already set justification, but it will also override the default style colors, which you don't likely want. You can look inside that VI to see how to set rows/column styles though, as you could pull out the style, then just override the justification in a custom VI.  Otherwise, that will have to be added as a custom method.

**Comment by smXplorer** [comment]
Thanks for the answers. The Edit mode problem is a none issue for standalone apps. What about the distinction between label and caption for columns (and I suppose the same issue exists for row labels)?

On a different topic, I have cloned your repository, but using LV 2015, I can't really contribute to the project, or everything would become illegible to your LV 2014. I suspect this is a general problem of LV. Although you would think that everything there is in a diagram could very well be saved in a text file... Anyone at NI reading this?

**Comment by unipsycho** [comment]
The columns names use data binding from the data table directly, so do need them to be unique.  There are labels and names though in the .net elements so as you suggest, it's likely easy to add both and be more flexible.  Rows likely are the same, but I've never personally used row labels, so not sure how that would need to be.

As for 2014vs2015, if you can contribute in 2015, that is fine with me.  i start this in 14 but may just upgrade.  My plan is to produce releases in mulitple versions as packed libraries so they can easily be used / installed with a VIP and pallettes anyway, so then they will have to be saved back to each version for release.  Definitley a pain in Labview, but workable.  If you ask me, those contributing will define the versions as I'd rather have help in 2015 then none if I'm using something older.

As to NI.  I've chatted with Burt Snover at NI about this control, as he is curious about it and contributing possible for use in his tag databus engine.  He raised similar concerns about versioning, and would likely use 2013 since for release.  Again, if its done with packed libraries for each version though, it won't matter.

**Comment by unipsycho** [comment]
Added a new properties to the columns, CAPTION, which allows a different caption to be used for display text, and allowing duplicates.  The original name is used for data binding this way, the CAPTION is simply the display.  You can leave it blank as in the example and it will inherit from the name.
